### PR TITLE
Typos and fixes

### PR DESCRIPTION
**Pull request by bentley**
The Hathitrust and Internet Archive scans are still copyright‐locked, but [Google has a scan available](https://www.google.com/books/edition/The_Murder_of_Roger_Ackroyd/afL6C6J-zmEC). All non‐editorial changes bring us closer to that scan.

I re‐italicized *inutile* and *amour propre*, even though they’re in Merriam‐Webster, because the intent is clearly to emphasize the foreignness of Poirot’s vocabulary.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks, good catches! 

One note: For the change in chapter 17, `As a matter of fact, though`, the master branch is as-is in print in the scans we're using, which are available on HT https://babel.hathitrust.org/cgi/pt?id=uc1.32106001974036

I don't think that correction is an obvious typo because having a comma there changes the meaning of the sentence. So let's stick with the scans we're using now and leave that comma in.

Can you fix that? Thanks!

**Comment by bentley** [comment]
At first I was very resistant, but after some thought I agree that we should leave the meaning as‐is. Entirely too much detail follows, in order to explain my change of heart:

Every print edition I could find used the alternative reading of the sentence. For clarity, by “alternative reading” I mean using “though” to subordinate the clause:

>As a matter of fact,

>though Flora is like all these young girls nowadays, with no veneration for their betters and thinking they know best on every subject under the sun,

>I don’t for a minute believe she’d kill even a chicken.

I saw this in a 1943, a 1977, and a 1990 edition.

I’ll use “original reading” to refer to how I now believe it was intended to be read:

>As a matter of fact, though,

>Flora is like all these young girls nowadays, with no veneration for their betters and thinking they know best on every subject under the sun.

>I don’t for a minute believe she’d kill even a chicken.

>But there it is.

The reason this reading makes more sense is that in context, the point of the paragraph is to opine that Flora *could* have committed murder.

> I’m not saying she <em>did</em>, James. I’m saying she <em>could</em> have done. As a matter of fact, though, Flora is like all these young girls nowadays, with no veneration for their betters and thinking they know best on every subject under the sun. I don’t for a minute believe she’d kill even a chicken. But there it is. <abbr>Mr.</abbr> Raymond and Major Blunt have alibis. <abbr>Mrs.</abbr> Ackroyd’s got an alibi. Even that Russell woman seems to have one⁠—and a good job for her it is she has. Who is left? Only Ralph and Flora! And say what you will, I don’t believe Ralph Paton is a murderer. A boy we’ve known all our lives.
￼
<p>Or, simplified:

> Flora could have killed Ackroyd.

> Flora has no veneration, etc.

> I don’t think she would kill, but it’s possible.

> Everyone has an alibi except Flora and Ralph.

> And it couldn’t have been Ralph.

HT is the only print edition I’m aware of with this reading. There are a number of shoddy, hastily‐produced 2022 ebook editions (and one pleasing, thoughtfully produced 2022 ebook edition ☺) that are clearly based on this printing.

I’ll note that in this reading, the comma before the chicken clause is ungrammatical. Sometimes I let commas between independent clauses slide, but in this case the chicken clause is clearly meant to be paired with the sentence *after*, not the one before. Happily, we can replace this comma with a period without changing the meaning, and without even changing any character’s case. Notably, there is an *audiobook* edition (narrated by Hugh Fraser) that uses this same reading, with an audible full stop after “sun.” So here is a new commit making *that* change.

**Comment by bentley** [comment]
Strike that! Let me gather my thoughts, because of course just as I submit the comment I change my mind again.

**Comment by bentley** [comment]
Okay I’ve dropped the chapter 17 change. I still have thoughts about it, so I may open a separate pull request for it in the future with further reasoning.

**Comment by acabal** [comment]
Thanks! IMHO regardless of punctuation the meaning of that clause is functionally the same either way, and it's easier to reason about in the future if we follow print. (In case we change it and then someone shows up years from now and says we have weird typos in this line.)

**Pull request merged**
